name: "Terraform Manual Deploy"

on:
  push:
    branches: [ "main" ]
    
concurrency:
  group: terraform-production
  cancel-in-progress: false
  
permissions:
  id-token: write
  contents: read

jobs:
  # JOB 1: Plan
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/769170094354/locations/global/workloadIdentityPools/test-github-terraform/providers/github-provider'
          service_account: 'github-terraform-sa@cloudside-academy.iam.gserviceaccount.com'
      
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan

  # JOB 2: The "Manual Approval"
  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/769170094354/locations/global/workloadIdentityPools/test-github-terraform/providers/github-provider'
          service_account: 'github-terraform-sa@cloudside-academy.iam.gserviceaccount.com'

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      # We use -auto-approve because YOUR click in GitHub was the "Yes"
      - run: terraform apply -auto-approve
